package crypto

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"io"

	"golang.org/x/crypto/curve25519"
	"golang.org/x/crypto/hkdf"
)

const (
	// KeySize is the size of X25519 keys in bytes
	KeySize = 32
)

// KeyPair holds a private and public key pair
type KeyPair struct {
	PrivateKey [KeySize]byte
	PublicKey  [KeySize]byte
}

// GenerateKeyPair generates a new X25519 key pair
func GenerateKeyPair() (*KeyPair, error) {
	var privateKey [KeySize]byte
	var publicKey [KeySize]byte

	// Generate random private key
	if _, err := rand.Read(privateKey[:]); err != nil {
		return nil, fmt.Errorf("generate private key: %w", err)
	}

	// Clamp private key (X25519 requirement)
	privateKey[0] &= 248
	privateKey[31] &= 127
	privateKey[31] |= 64

	// Derive public key
	curve25519.ScalarBaseMult(&publicKey, &privateKey)

	return &KeyPair{
		PrivateKey: privateKey,
		PublicKey:  publicKey,
	}, nil
}

// PrivateKeyBase64 returns the private key as base64
func (kp *KeyPair) PrivateKeyBase64() string {
	return base64.StdEncoding.EncodeToString(kp.PrivateKey[:])
}

// PublicKeyBase64 returns the public key as base64
func (kp *KeyPair) PublicKeyBase64() string {
	return base64.StdEncoding.EncodeToString(kp.PublicKey[:])
}

// ParsePrivateKey parses a base64 encoded private key and derives the
// public key. Bytes are copied verbatim — X25519 private keys MUST be
// clamped per RFC 7748 §5, but x/crypto/curve25519's scalar-mult
// internally re-clamps before use so a non-clamped imported key still
// produces correct outputs. Keys generated by GenerateKeyPair are
// always pre-clamped.
func ParsePrivateKey(b64 string) (*KeyPair, error) {
	data, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return nil, fmt.Errorf("decode private key: %w", err)
	}

	if len(data) != KeySize {
		return nil, fmt.Errorf("invalid private key length: %d (expected %d)", len(data), KeySize)
	}

	var privateKey [KeySize]byte
	var publicKey [KeySize]byte
	copy(privateKey[:], data)

	// Derive public key from private key
	curve25519.ScalarBaseMult(&publicKey, &privateKey)

	return &KeyPair{
		PrivateKey: privateKey,
		PublicKey:  publicKey,
	}, nil
}

// ParsePublicKey parses a base64 encoded public key. Rejects an all-zero
// key up front so an operator with a typo'd or attacker-supplied peer
// pubkey gets a clear error at boot rather than a silent AEAD failure
// later (curve25519.X25519 already rejects a fixed list of low-order
// points, but flagging all-zero here surfaces the most common pasted-
// nothing failure mode).
func ParsePublicKey(b64 string) ([KeySize]byte, error) {
	var publicKey [KeySize]byte

	data, err := base64.StdEncoding.DecodeString(b64)
	if err != nil {
		return publicKey, fmt.Errorf("decode public key: %w", err)
	}

	if len(data) != KeySize {
		return publicKey, fmt.Errorf("invalid public key length: %d (expected %d)", len(data), KeySize)
	}

	copy(publicKey[:], data)
	var zero [KeySize]byte
	if subtle.ConstantTimeCompare(publicKey[:], zero[:]) == 1 {
		return publicKey, errors.New("peer public key is all-zero (invalid)")
	}
	return publicKey, nil
}

// ComputeSharedSecret computes the shared secret using X25519 ECDH.
// Hard-fails if the resulting shared secret is all-zero — defense in
// depth on top of curve25519.X25519's low-order-point rejection, since
// not all low-order or twist points are caught by every library
// version, and an all-zero shared secret would silently degrade the
// AEAD to a known-key cipher.
func ComputeSharedSecret(privateKey [KeySize]byte, peerPublicKey [KeySize]byte) ([KeySize]byte, error) {
	var sharedSecret [KeySize]byte

	result, err := curve25519.X25519(privateKey[:], peerPublicKey[:])
	if err != nil {
		return sharedSecret, fmt.Errorf("compute shared secret: %w", err)
	}

	copy(sharedSecret[:], result)
	var zero [KeySize]byte
	if subtle.ConstantTimeCompare(sharedSecret[:], zero[:]) == 1 {
		return sharedSecret, errors.New("shared secret is all-zero (peer key is low-order point)")
	}
	return sharedSecret, nil
}

// DeriveSessionKeys derives encryption keys from the shared secret using HKDF (RFC 5869).
// Returns: (sendKey, receiveKey, error)
// The salt is fixed (no per-session randomness needed since X25519 shared secrets
// are already unique per key pair). Info strings differentiate send/receive keys.
func DeriveSessionKeys(sharedSecret [KeySize]byte, isInitiator bool) ([KeySize]byte, [KeySize]byte, error) {
	var sendKey, recvKey [KeySize]byte

	salt := []byte("quiccochet-v2-session-keys")

	// Derive initiator→responder key
	irReader := hkdf.New(sha256.New, sharedSecret[:], salt, []byte("initiator-to-responder"))
	if _, err := io.ReadFull(irReader, sendKey[:]); err != nil {
		return sendKey, recvKey, fmt.Errorf("derive send key: %w", err)
	}

	// Derive responder→initiator key
	riReader := hkdf.New(sha256.New, sharedSecret[:], salt, []byte("responder-to-initiator"))
	if _, err := io.ReadFull(riReader, recvKey[:]); err != nil {
		return sendKey, recvKey, fmt.Errorf("derive recv key: %w", err)
	}

	// Swap keys based on role (initiator sends, responder receives with same key)
	if !isInitiator {
		sendKey, recvKey = recvKey, sendKey
	}

	return sendKey, recvKey, nil
}
